language: python
python:
  - 2.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xz-utils
  
install:
  - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
  - sudo apt-get install -qq pep8 pyflakes
  - python bootstrap.py
  - bin/buildout
  - ls -l ./parts/wkhtmltopdf/
  - ls -l ./parts/wkhtmltopdf/wkhtmltox/bin
  - ./parts/wkhtmltopdf/wkhtmltox/bin/wkhtmltopdf || true
  - ./parts/wkhtmltopdf/wkhtmltox/bin/wkhtmltopdf --version || true
  - ./parts/wkhtmltopdf/wkhtmltox/bin/wkhtmltopdf --help || true
  - parts/wkhtmltopdf/wkhtmltox/bin/wkhtmltopdf --help || true

script:
  - bin/test -m collective.sendaspdf
  - pyflakes collective
  - pep8 collective 
  - parts/wkhtmltopdf/wkhtmltopdf http://www.google.com google.pdf

notifications:
  irc:
  email:
    - f.van.dijk@zestsoftware.nl
    - m.van.rees@zestsoftware.nl
