language: python
python:
  - 2.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xz-utils libxrender1 gdebi-core pep8 pyflakes
  - curl --location --output wkhtmltopdf.deb http://downloads.sourceforge.net/project/wkhtmltopdf/archive/0.12.2/wkhtmltox-0.12.2_linux-trusty-i386.deb
  - sudo gdebi --non-interactive wkhtmltopdf.deb
  - wkhtmltopdf http://www.google.com google.pdf

install:
  - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
  - python bootstrap.py
  - bin/buildout

script:
  - bin/test -m collective.sendaspdf
  - pyflakes collective
  - pep8 collective 

notifications:
  irc:
  email:
    - f.van.dijk@zestsoftware.nl
    - m.van.rees@zestsoftware.nl
