language: python
python:
  - 2.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xz-utils libxrender1
  
install:
  - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
  - sudo apt-get install -qq pep8 pyflakes
  - python bootstrap.py
  - bin/buildout install wkhtmltopdf wkhtmltopdf_install
  - ls -l parts/wkhtmltopdf/
  - ls -l parts/wkhtmltopdf/bin
  - ls -l parts/wkhtmltopdf/bin/wkhtmltopdf || true
  - parts/wkhtmltopdf/bin/wkhtmltopdf || true
  - parts/wkhtmltopdf/bin/wkhtmltopdf http://www.google.com google.pdf || true
  - bin/buildout

script:
  - bin/test -m collective.sendaspdf
  - pyflakes collective
  - pep8 collective 

notifications:
  irc:
  email:
    - f.van.dijk@zestsoftware.nl
    - m.van.rees@zestsoftware.nl
