language: python
python:
  - 2.7

install:
  - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
  - sudo apt-get install -qq pep8 pyflakes
  - python bootstrap.py
  - bin/buildout
  - parts/wkhtmltopdf/wkhtmltopdf --version
  - parts/wkhtmltopdf/wkhtmltopdf --help

script:
  - bin/test -m collective.sendaspdf
  - pyflakes collective
  - pep8 collective 
  - parts/wkhtmltopdf/wkhtmltopdf http://www.google.com google.pdf

notifications:
  irc:
  email:
    - v.pretre@zestsoftware.nl
    - m.van.rees@zestsoftware.nl
